// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: led

#include "ui.h"
#include <esp_now.h>
#include <string.h>

extern struct_message myData;
extern uint8_t receiverMac[];

void Led_on(void) {
  strcpy(myData.command, "ON");
  esp_now_send(receiverMac, (uint8_t *)&myData, sizeof(myData));
  Serial.println("Sent: ON");
}

void Led_off(void) {
  strcpy(myData.command, "OFF");
  esp_now_send(receiverMac, (uint8_t *)&myData, sizeof(myData));
  Serial.println("Sent: OFF");
}
