// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: led

#include "ui.h"

void Led_on(lv_event_t * e)
{
	// Your code here
}

void Led_off(lv_event_t * e)
{
	// Your code here
}
