// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: led

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Led_on(lv_event_t * e);
void Led_off(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
